// Auto-generated by tools/bitmap2header.js — do not edit by hand.
// Source PNGs live in assets/screens/; regenerate with `npm run build:screens`.
#pragma once
#include <cstdint>

namespace screens {

// A monochrome bitmap packed in Adafruit GFX `drawBitmap` byte order:
// row-major, MSB = leftmost pixel, one byte per 8 horizontal pixels,
// rows padded up to the next byte boundary.
struct Screen {
    const uint8_t* data;
    uint8_t        width;
    uint8_t        height;
};

// An ordered sequence of Screen pointers — one directory of PNGs under
// assets/screens/ becomes one Animation, named after the directory.
// Frames are in natural-sort order of their filenames.
struct Animation {
    const Screen* const* frames;
    uint8_t              count;
};

extern const Screen sample;
extern const Screen key_A;
extern const Screen key_B;
extern const Screen key_C;
extern const Screen key_D;
extern const Screen key_E;
extern const Screen key_F;
extern const Screen key_G;
extern const Screen sharp;
extern const Screen splash_screen1;
extern const Screen splash_screen2;
extern const Screen splash_screen3;
extern const Screen splash_screen4;
extern const Screen splash_screen5;
extern const Screen splash_screen6;
extern const Screen splash_screen7;
extern const Screen splash_screen8;
extern const Screen splash_screen9;

extern const Animation key_screen;
extern const Animation splash_screen_animation;

} // namespace screens
